### ISSUE TITLE
Can´t break Mekanism Cable with Pickaxe

### ISSUE THREAD

**Issue by ankfritz** [Y0ungSandwich/LightlySalted#8]
Can´t break Mekanism Basic Universal Cable with Pickaxe (Tinker´s or Vanilla)
The Game chrashes/Shutdown

**Comment by emanb29** [comment]
+1. Crash log:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.46-beta.jar)
  LoadingHook (Mekanism-1.10.2-9.1.0.286.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 8/15/16 8:36 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=ticking, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in ExtendedBlockState{block=mcmultipart:multipart, properties=[ticking]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
    at mcmultipart.block.BlockMultipartContainer.func_176201_c(BlockMultipartContainer.java:408)
    at net.minecraft.block.Block.getHarvestTool(Block.java:1927)
    at net.minecraft.block.Block.isToolEffective(Block.java:1950)
    at net.minecraft.item.ItemTool.func_150893_a(ItemTool.java:59)
    at mekanism.tools.item.ItemMekanismPickaxe.func_150893_a(ItemMekanismPickaxe.java:78)
    at net.minecraft.item.ItemStack.func_150997_a(ItemStack.java:157)
    at net.minecraft.entity.player.InventoryPlayer.func_184438_a(InventoryPlayer.java:522)
    at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:808)
    at mcmultipart.multipart.Multipart.getStrength(Multipart.java:205)
    at mcmultipart.multipart.MultipartContainer.getHardness(MultipartContainer.java:350)
    at mcmultipart.block.BlockMultipartContainer.func_180647_a(BlockMultipartContainer.java:175)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:395)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:240)
    at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1459)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
    at mcmultipart.block.BlockMultipartContainer.func_176201_c(BlockMultipartContainer.java:408)
    at net.minecraft.block.Block.getHarvestTool(Block.java:1927)
    at net.minecraft.block.Block.isToolEffective(Block.java:1950)
    at net.minecraft.item.ItemTool.func_150893_a(ItemTool.java:59)
    at mekanism.tools.item.ItemMekanismPickaxe.func_150893_a(ItemMekanismPickaxe.java:78)
    at net.minecraft.item.ItemStack.func_150997_a(ItemStack.java:157)
    at net.minecraft.entity.player.InventoryPlayer.func_184438_a(InventoryPlayer.java:522)
    at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:808)
    at mcmultipart.multipart.Multipart.getStrength(Multipart.java:205)
    at mcmultipart.multipart.MultipartContainer.getHardness(MultipartContainer.java:350)
    at mcmultipart.block.BlockMultipartContainer.func_180647_a(BlockMultipartContainer.java:175)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:395)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:240)
    at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1459)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['emanb29'/100439, l='MpServer', x=403.83, y=77.56, z=-185.93]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (677,70,261), Chunk: (at 5,4,5 in 42,16; contains blocks 672,0,256 to 687,255,271), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
    Level time: 21656743 game time, 21868571 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 68 total; [EntityZombie['Zombie'/109571, l='MpServer', x=378.50, y=22.00, z=-226.50], EntityBabySkeleton['Baby Skeleton'/115717, l='MpServer', x=444.50, y=14.00, z=-179.50], EntityPlayerSP['emanb29'/100439, l='MpServer', x=402.50, y=77.10, z=-187.50], EntityEnderman['Enderman'/119054, l='MpServer', x=412.50, y=37.00, z=-171.50], EntityBabySkeleton['Baby Skeleton'/108305, l='MpServer', x=421.50, y=26.00, z=-239.50], EntityCreeper['Creeper'/112916, l='MpServer', x=373.50, y=64.00, z=-237.50], EntityBat['Bat'/108828, l='MpServer', x=418.81, y=23.83, z=-226.97], EntitySkeleton['Skeleton'/104990, l='MpServer', x=359.27, y=19.00, z=-167.52], EntityChicken['Chicken'/100654, l='MpServer', x=401.08, y=63.00, z=-243.12], EntityChicken['Chicken'/100689, l='MpServer', x=463.80, y=73.00, z=-242.19], EntityItem['item.item.dyePowder.black'/118608, l='MpServer', x=349.60, y=56.00, z=-211.55], EntityHorse['Skeleton Horse'/100691, l='MpServer', x=450.12, y=71.00, z=-181.90], EntitySheep['Sheep'/100690, l='MpServer', x=459.74, y=71.00, z=-165.51], EntityHorse['Skeleton Horse'/100692, l='MpServer', x=456.15, y=71.00, z=-178.28], EntityBat['Bat'/115545, l='MpServer', x=448.75, y=55.00, z=-219.50], EntityBat['Bat'/115548, l='MpServer', x=455.40, y=59.91, z=-212.33], EntityHorse['Skeleton Horse'/100703, l='MpServer', x=469.15, y=70.00, z=-216.34], EntityChicken['Chicken'/100707, l='MpServer', x=465.50, y=74.00, z=-234.50], EntityHorse['Skeleton Horse'/100711, l='MpServer', x=471.00, y=69.00, z=-189.00], EntitySheep['Sheep'/100713, l='MpServer', x=469.59, y=69.00, z=-186.25], EntityBabySkeleton['Baby Skeleton'/118377, l='MpServer', x=424.50, y=22.00, z=-236.50], EntityHorse['Skeleton Horse'/100712, l='MpServer', x=478.00, y=69.00, z=-181.00], EntitySheep['Sheep'/100715, l='MpServer', x=480.69, y=69.00, z=-195.65], EntitySquid['Squid'/120428, l='MpServer', x=375.40, y=60.11, z=-207.40], EntityZombie['Zombie'/112238, l='MpServer', x=395.50, y=20.00, z=-245.50], EntitySheep['Sheep'/100723, l='MpServer', x=465.55, y=69.00, z=-147.45], EntitySquid['Squid'/120436, l='MpServer', x=369.60, y=60.75, z=-223.43], EntitySquid['Squid'/119165, l='MpServer', x=346.16, y=60.37, z=-207.26], EntitySquid['Squid'/119167, l='MpServer', x=341.40, y=60.80, z=-212.20], EntitySquid['Squid'/119166, l='MpServer', x=353.10, y=58.00, z=-211.66], EntitySheep['Sheep'/95876, l='MpServer', x=364.87, y=64.00, z=-252.67], EntitySheep['Sheep'/100743, l='MpServer', x=469.59, y=65.00, z=-111.45], EntitySheep['Sheep'/100747, l='MpServer', x=466.79, y=67.00, z=-115.45], EntitySheep['Sheep'/100749, l='MpServer', x=467.11, y=67.00, z=-114.45], EntitySheep['Sheep'/100748, l='MpServer', x=467.33, y=66.00, z=-113.45], EntityPlayerSP['emanb29'/100439, l='MpServer', x=403.83, y=77.56, z=-185.93], EntityChicken['Chicken'/100503, l='MpServer', x=338.61, y=70.00, z=-189.51], EntityBat['Bat'/120477, l='MpServer', x=482.69, y=45.00, z=-223.97], EntityChicken['Chicken'/100511, l='MpServer', x=344.51, y=68.00, z=-196.11], EntityChicken['Chicken'/100513, l='MpServer', x=355.43, y=70.00, z=-187.80], EntityChicken['Chicken'/100512, l='MpServer', x=358.88, y=70.00, z=-184.62], EntityCow['Cow'/100515, l='MpServer', x=345.49, y=73.00, z=-174.22], VengeanceSpirit['Vengeance Spirit'/116899, l='MpServer', x=379.25, y=64.00, z=-238.75], EntityCow['Cow'/100514, l='MpServer', x=336.50, y=70.00, z=-167.50], EntityCow['Cow'/100517, l='MpServer', x=344.73, y=67.00, z=-127.18], EntityItem['item.item.dyePowder.black'/120233, l='MpServer', x=342.38, y=60.00, z=-211.90], EntitySheep['Sheep'/100520, l='MpServer', x=357.69, y=76.00, z=-153.35], EntityCow['Cow'/100523, l='MpServer', x=345.84, y=66.00, z=-104.50], EntityCreeper['Creeper'/118701, l='MpServer', x=483.50, y=30.00, z=-251.50], EntityCreeper['Creeper'/118700, l='MpServer', x=481.50, y=30.00, z=-251.50], EntityCreeper['Creeper'/118702, l='MpServer', x=483.50, y=30.00, z=-253.50], EntityCreeper['Creeper'/118709, l='MpServer', x=481.50, y=30.00, z=-251.50], EntityCow['Cow'/100537, l='MpServer', x=333.49, y=67.00, z=-195.18], EntityZombie['Zombie'/119737, l='MpServer', x=342.50, y=41.00, z=-122.50], EntityZombie['Zombie'/120507, l='MpServer', x=422.50, y=24.00, z=-244.50], EntityCow['Cow'/100541, l='MpServer', x=347.85, y=64.00, z=-229.34], EntityZombie['Zombie'/120520, l='MpServer', x=437.50, y=33.00, z=-236.50], EntitySlime['Slime'/118475, l='MpServer', x=477.43, y=16.00, z=-224.21], EntityCreeper['Creeper'/110797, l='MpServer', x=403.50, y=20.00, z=-223.50], EntityZombie['Zombie'/118477, l='MpServer', x=421.50, y=43.00, z=-222.50], EntityCreeper['Creeper'/110796, l='MpServer', x=408.50, y=20.00, z=-222.50], EntityCreeper['Creeper'/108497, l='MpServer', x=421.50, y=43.00, z=-220.50], EntityCreeper['Creeper'/120025, l='MpServer', x=464.50, y=51.00, z=-222.50], EntitySheep['Sheep'/100575, l='MpServer', x=411.36, y=63.00, z=-256.24], EntityCow['Cow'/100579, l='MpServer', x=352.64, y=73.00, z=-165.18], EntityChicken['Chicken'/100580, l='MpServer', x=367.49, y=79.00, z=-142.87], EntitySquid['Squid'/118503, l='MpServer', x=348.82, y=58.90, z=-210.92], EntityWitch['Witch'/120314, l='MpServer', x=429.50, y=27.00, z=-180.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge,sponge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1575571504 bytes (1502 MB) / 3719000064 bytes (3546 MB) up to 4225236992 bytes (4029 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx4096M -XX:MetaspaceSize=256M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.1.2011 49 mods loaded, 49 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2011-universal.jar) 
    UCHIJA  Forge{12.18.1.2011} [Minecraft Forge] (forge-1.10.2-12.18.1.2011-universal.jar) 
    UCHIJA  autopackager{1.6.3} [AutoPackager] (autopackager-1.6.3.jar) 
    UCHIJA  bagginses{2.4.2d} [Bagginses] (Bagginses-1.10-3.0.3.jar) 
    UCHIJA  Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJA  JEI{3.7.9.236} [Just Enough Items] (jei_1.10.2-3.7.9.236.jar) 
    UCHIJA  BloodMagic{1.9.4-2.0.3-53} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.3-53.jar) 
    UCHIJA  Botania{r1.8-312} [Botania] (Botania-unofficial.r1.8-312.jar) 
    UCHIJA  chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-MC1.9.4-0.0.6.33.jar) 
    UCHIJA  mcmultipart{1.2.0_72} [MCMultiPart] (MCMultiPart-experimental-1.2.0_72-universal.jar) 
    UCHIJA  chiselsandbits{11.8} [Chisels & Bits] (chiselsandbits-11.8.jar) 
    UCHIJA  cyclopscore{0.7.3} [Cyclops Core] (CyclopsCore-1.9.4-0.7.3.jar) 
    UCHIJA  commoncapabilities{1.1.1} [CommonCapabilities] (CommonCapabilities-1.9.4-1.1.1.jar) 
    UCHIJA  ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
    UCHIJA  deepresonance{1.2.0beta35} [DeepResonance] (deepresonance-1.9.4-1.2.0beta35.jar) 
    UCHIJA  endercore{1.10.2-0.4.1.46-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.46-beta.jar) 
    UCHIJA  Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJA  EnderIO{1.10.2-3.0.1.81_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.81_beta.jar) 
    UCHIJA  shetiphiancore{3.3.0} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.0.jar) 
    UCHIJA  endertanks{1.4.1} [EnderTanks] (endertanks-1.10.0-1.4.1.jar) 
    UCHIJA  enderutilities{0.6.5} [Ender Utilities] (enderutilities-1.10.2-0.6.5.jar) 
    UCHIJA  evilcraft{0.10.7} [EvilCraft] (EvilCraft-1.9.4-0.10.7.jar) 
    UCHIJA  ezstorage{2.2.2} [EZStorage 2] (ezstorage-2.2.2.jar) 
    UCHIJA  forestry{5.2.7.220} [Forestry] (forestry_1.10.2-5.2.7.220.jar) 
    UCHIJA  integrateddynamics{0.4.2} [Integrated Dynamics] (IntegratedDynamics-1.9.4-0.4.2.jar) 
    UCHIJA  inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
    UCHIJA  IronChest{7.0.7.795} [Iron Chest] (ironchest-1.10.2-7.0.7.795.jar) 
    UCHIJA  journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJA  jeresources{0.4.6.44} [Just Enough Resources] (JustEnoughResources-1.10.2-0.4.6.44.jar) 
    UCHIJA  lightningcraft{2.4.4} [LightningCraft] (lightningcraft-2.4.4.jar) 
    UCHIJA  malisiscore{1.9.4-4.0.2} [MalisisCore] (malisiscore-1.9.4-4.0.2.jar) 
    UCHIJA  malisisdoors{1.9.4-5.0.1} [MalisisDoors] (malisisdoors-1.9.4-5.0.1.jar) 
    UCHIJA  mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
    UCHIJA  Mekanism{9.1.0} [Mekanism] (Mekanism-1.10.2-9.1.0.286.jar) 
    UCHIJA  MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.1.0.286.jar) 
    UCHIJA  MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.10.2-9.1.0.286.jar) 
    UCHIJA  netheressence{6.0.1.5} [Nether Essence] (NetherEssence-Forge-6.0.1.5.jar) 
    UCHIJA  openharvest{1.1.0} [Open Harvest] (openharvest-1.1.0.jar) 
    UCHIJA  randomthings{3.7.4} [Random Things] (RandomThings-MC1.10-3.7.4.jar) 
    UCHIJA  xreliquary{1.10.2-1.3.2.434} [Reliquary] (Reliquary-1.10.2-1.3.2.434.jar) 
    UCHIJA  rftools{5.10} [RFTools] (rftools-1.10-5.10.jar) 
    UCHIJA  Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJA  soulshardstow{1.10.2-2.5.5-39} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.5.5-39.jar) 
    UCHIJA  tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
    UCHIJA  WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.10-1.1.7.jar) 
    UCHIJA  waterstrainer{1.1.0} [Water Strainer] (WaterStrainer-1.9.4-1.1.0.jar) 
    UCHIJA  icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.200.jar) 
    UCHIJA  wawla{2.3.0.194} [What Are We Looking At] (Wawla-1.10.2-2.3.0.200.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.46-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingHook (Mekanism-1.10.2-9.1.0.286.jar)

FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.81' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

    EnderIO: No known problems detected.
    Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/F:/ATLauncher/Instances/LightlySalted/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/F:/ATLauncher/Instances/LightlySalted/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/F:/ATLauncher/Instances/LightlySalted/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/F:/ATLauncher/Instances/LightlySalted/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/F:/ATLauncher/Instances/LightlySalted/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/F:/ATLauncher/Instances/LightlySalted/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/F:/ATLauncher/Instances/LightlySalted/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/F:/ATLauncher/Instances/LightlySalted/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/F:/ATLauncher/Instances/LightlySalted/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/F:/ATLauncher/Instances/LightlySalted/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/TileEnergyHandler.class

    Launched Version: 1.10.2
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 970M/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.81, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: Sphax PureBDcraft  64x MC17.zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 8x Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
```
